### ISSUE TITLE
Errors and Ambiguities in The Swift Programming Language (Swift 5.7)

### ISSUE THREAD

**Issue by tadbyt** [apple/swift-book#116]
The attachment contains a list of minor issues in The Swift Programming Language (Swift 5.7) document.  The edition reviewed is the ePub download from swift.org, not the online version.  These issues are identified for possible resolution in the release of this document for a subsequent version of Swift.
[SPL 5.7 Issues.docx](https://github.com/apple/swift-book/files/10962304/SPL.5.7.Issues.docx)

rdar://105507343

**Comment by amartini51** [comment]
Thanks for taking the time to review TSPL in detail and to write up notes about what you've found!

The best way we can make progress here is to create specific, actionable bugs.  Because there's usually a 1:1 mapping between issues and pull requests, that can help you scope your issues: If a change will need pull requests to review, you should write separate issues.  This repository's GitHub issues templates can help you provide the necessary  information in a structured way.  For general guidance about reporting bugs, see [Writing your feedback](https://developer.apple.com/bug-reporting/#report) and [How to file great bug reports](https://developer.apple.com/news/?id=vvrgkboh).

Because Swift is an open-source project, I also encourage you to write up your suggested corrections for minor errors, or to propose an outline of changes where you find something unclear.  You can pitch larger changes on the forums and use pull requests to request review for smaller changes.

As a note, the page numbers from the ePUB depend on the size of your screen.  I generally find the best way to identify a typo or similar error is to copy the sentence or other nearby context it appears in.  This enables "find on page" or `git grep` to locate the error in the source file.
