### ISSUE TITLE
Incorrect encoding used in 4CC macro example

### ISSUE THREAD

**Issue by grynspan** [apple/swift-book#171]
### Location

https://github.com/apple/swift-book/blob/main/TSPL.docc/LanguageGuide/Macros.md?plain=1#L540

### Description

Four-character-codes as used by Apple are encoded as MacRoman, not as ASCII. The macro here, as implemented, will reject valid 4CCs.

### Correction

As MacRoman is not supported by the Swift standard library, a fix is not trivial. Foundation supports converting from Unicode to MacRoman, so a fix could use existing Foundation API to do the conversion instead.

**Comment by amartini51** [comment]
This is an example of macros, not intended to be a fully functional API for generating four-character codes.  As with many other examples in TSPL, it intentionally limits its functionality in the interest of simplicity.  This example macro was chosen because it is complex enough to not just be a trivial toy, but simple enough that the implementation details don't get in the way.
