### ISSUE TITLE
Will the main authors be adding complete, unabridged information about macros?

### ISSUE THREAD

**Issue by shyamalschandra** [apple/swift-book#185]
### Location

https://github.com/apple/swift-book/blob/main/TSPL.docc/LanguageGuide/Macros.md

### Description

There isn't complete, unabridged information about macros.

### Correction

Every possible macro and detailed information about them.

**Comment by amartini51** [comment]
There are no macros built into the Swift language, which is why this book doesn't document any macros.  However, one of the challenges of documenting Swift macros is how several different projects come together to support this feature.

The macros from the Swift standard library are defined in source here https://github.com/apple/swift/blob/main/stdlib/public/core/Macros.swift and documented here http://developer.apple.com/documentation/swift/macros

Swift Syntax is a separate package (not part of the language or the standard library).  It's source code is at https://github.com/apple/swift-syntax which links to https://swiftpackageindex.com/apple/swift-syntax/509.0.0/documentation/swiftsyntax as the package documentation website.

Is there something else you're looking for documentation of?

**Comment by shyamalschandra** [comment]
Really, @amartini51!

Please see: https://docs.swift.org/swift-book/documentation/the-swift-programming-language/macros/

I beg to differ.  Please show **complete, unabridged** information about the macros.

Every **possible** macro and **detailed** information about them.

**Comment by amartini51** [comment]
Let's be constructive. What's missing from that chapter?  Please be specific, concrete, and actionable.  Repeating yourself in doesn't add any information to the discussion.

Macros are a difficult topic to learn, in part because they involve pieces from the language + the standard library + the Swift Syntax library, each of which own their own documentation.  Fortunately, all of these are part of the open source Swift project — you can suggest (and implement!) improvements to all of them.  If you have ideas about how to make this topic easier to learn, please share them.

Here's an example of a good bug, to help get you started.  During Doug Gregor's review of a recent macros PR, he pointed out that TSPL has not yet been updated for SE-0402 — conformance macros have been replaced by extensions macros.

**Comment by adozenlines** [comment]
I think what is being asked or expressed is the current documentation for custom macros is lacking complete examples and seems like it was rushed leaving a lot up for interpretation and frustration.

**Comment by amartini51** [comment]
Closing this as a general, known issue that we're already tracking — no additional comments from the originator in ~3 months.
