### ISSUE TITLE
Incorporate the Operator Precedence into Advanced Operators

### ISSUE THREAD

**Issue by tadbyt** [apple/swift-book#240]
### Location

https://developer.apple.com/documentation/swift/operator-declarations/
https://docs.swift.org/swift-book/documentation/the-swift-programming-language/advancedoperators

### Description

Incorporate the content of the _Operator Declarations_ article into the _Advanced Operators_ section.  The pointwise operators would also require a new subsection in the _Advanced Operators_ sections.  Perhaps space could be made by moving the _Results Builders_ subsection to its own section.

### Motivation

This information, at least the portion related to fundamental types, should have always been in the TSPL book.  This is the first language that I have encountered where that information was not part of the language specification.

### Alternatives Considered

Duplicating the portion relevant to the fundamental types.  This raises the issue of duplicate information in the TSPL and the article, which could be an issue down the road should the precedence levels be adjusted, in maintaining both documents to keep their information synchronized.

**Comment by amartini51** [comment]
This probably shouldn't be changed, but it's a difficult piece of documentation to organize.

One conceptual point of clarification — part of the reason that the operator precedence isn't part of TSPL or a formal language specification (which Swift doesn't have) is that the operators aren't part of the language.  In a language like C, the operators and their precedences are defined as part of the definition of the language.  In Swift, they're just one more API defined in the standard library in Swift code.

TSPL isn't meant to be a complete list of all operators.  The purpose of the Advanced Operators chapter is to introduces folks to operators that they might not have used in other languages.  Some of the documentation there really belongs on the reference for the specific operators, not in TSPL, but at the time of original publication for Swift 1 there was no API reference for the standard library.  We'd also have to extend `docc` and possibly the parts of the compiler that depends on, to be able to document an operator as a symbol rather than documenting only places where an operator is implemented.  (The difference between `prefix operator +++` and the `func` that implements it.)

The pointwise operators are a good counter-example.  They're not even from the standard library — they come from [SIMD](https://developer.apple.com/documentation/swift/simd).

As you read through Advanced Operators today, you'll see places where it intentionally cross references the Operator Declarations reference article — like for a list of all operators and their precedences.  That's specifically to avoid the issue you mentioned around duplicating information.
